# Generated by Django 3.2.8 on 2025-01-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_open_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='open_id',
            new_name='openid',
        ),
    ]
